# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install node js
        uses: actions/setup-node@v3.4.1

      # Runs a set of commands using the runners shell
      - name: install dependancies 
        run: npm install -g @angular/cli
        
      - name: install npm dependancies 
        run: npm i
        
      - name: build deployment version 
        run: ng build --prod
          
      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          github_token: $\{{ secrets.ACTIONTOKEN }}
          branch: deployment
        # folder: architect
